# GitHub adds these metadata via the site.github namespace:
# https://jekyll.github.io/github-metadata/site.github/

remote_theme: fongandrew/hydeout
plugins:
  - jekyll-feed

title: Title
description: Work in progress!
author: Mike Klimek
version:
sidebar_home_link: true
sidebar_blog_link:
paginate: 5

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
