# GitHub adds these metadata via the site.github namespace:
# https://jekyll.github.io/github-metadata/site.github/

title: Title
description: >-
  Multi
  Line
  Description
author: Mike Klimek

version:
sidebar_home_link:
sidebar_blog_link:

remote_theme: fongandrew/hydeout
paginate: 5
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
