# accessed via {{ site.title }}, {{ site.email }}, and so on.
title: Title
description: >-
  Multi
  Line
  Description
domain: tetr4.github.io
url: https://tetr4.github.io
baseurl: / # subpath, e.g. /blog

remote_theme: fongandrew/hydeout
paginate: 5
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
